### ISSUE TITLE
Non of my current Scratch 1.4 projects work fully

### ISSUE THREAD

**Issue by mobluse** [tjvr/skip#3]
I have a Scratch-studio with only Scratch 1.4-projects https://scratch.mit.edu/studios/244489/, but non of them works now. Some shows sprites or draws something, but non of them works fully (and even not in a useful way). You can download all the projects in the studio in Raspbian with:
    curl -L http://scratch.mit.edu/site-api/projects/in/244489/1/ 2> /dev/null | sed -n 's|._data-id=\"([0-9]_)\".*|\1|p' | while read proj; do curl -L -o $proj.sb http://projects.scratch.mit.edu/internalapi/project/$proj/get/; done

I then tested them one by one in Raspbian using e.g.
    python /usr/local/lib/python2.7/dist-packages/skip/pygame_screen.py 13197934.sb
    python /usr/local/lib/python2.7/dist-packages/skip/pygame_screen.py 12957158.sb
One problem is due to that variables are not displayed, but there are also other errors.

**Comment by tjvr** [comment]
That doesn't surprise me. Skip's still very experimental, and that's unlikely to change!

I'm going to close this issue—I'm aware that Skip doesn't run Scratch projects very well :) If you can isolate a specific bug or missing feature, then do raise an issue!
